In [1]:
import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from ydata_profiling import ProfileReport
from ydata_profiling.config import Settings

/Users/zachalabastro/Desktop/LENA Internship/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
db = 'northwind.db'
conn = sqlite3.connect(db)

In [3]:
all_data = pd.read_sql_query(
    "SELECT * FROM sqlite_master;",
    conn
)

# Show DataFields
all_data

,type,name,tbl_name,rootpage,sql
0,table,Categories,Categories,2,CREATE TABLE [Categories]\n( [CategoryID]...
1,table,sqlite_sequence,sqlite_sequence,3,"CREATE TABLE sqlite_sequence(name,seq)"
2,table,CustomerCustomerDemo,CustomerCustomerDemo,28,CREATE TABLE [CustomerCustomerDemo](\n [Cust...
3,index,sqlite_autoindex_CustomerCustomerDemo_1,CustomerCustomerDemo,29,None
4,table,CustomerDemographics,CustomerDemographics,30,CREATE TABLE [CustomerDemographics](\n [Cust...
5,index,sqlite_autoindex_CustomerDemographics_1,CustomerDemographics,31,None
6,table,Customers,Customers,32,CREATE TABLE [Customers]\n( [CustomerID] ...
7,index,sqlite_autoindex_Customers_1,Customers,33,None
8,table,Employees,Employees,37,CREATE TABLE [Employees]\n( [EmployeeID] ...
9,table,EmployeeTerritories,EmployeeTerritories,67,CREATE TABLE [EmployeeTerritories](\n [Emplo...
10,index,sqlite_autoindex_EmployeeTerritories_1,EmployeeTerritories,68,None
11,table,Order Details,Order Details,69,CREATE TABLE [Order Details](\n [OrderID]INT...
12,index,sqlite_autoindex_Order Details_1,Order Details,70,None
13,table,Orders,Orders,91,CREATE TABLE [Orders](\n [OrderID]INTEGER NO...
14,table,Products,Products,127,CREATE TABLE [Products](\n [ProductID]INTEGE...
15,table,Regions,Regions,131,CREATE TABLE [Regions](\n [RegionID]INTEGER ...
16,table,Shippers,Shippers,132,CREATE TABLE [Shippers](\n [ShipperID]INTEGE...
17,table,Suppliers,Suppliers,133,CREATE TABLE [Suppliers](\n [SupplierID]INTE...
18,table,Territories,Territories,134,CREATE TABLE [Territories](\n [TerritoryID]T...
19,index,sqlite_autoindex_Territories_1,Territories,135,None
20,view,Alphabetical list of products,Alphabetical list of products,0,CREATE VIEW [Alphabetical list of products] \n...
21,view,Current Product List,Current Product List,0,CREATE VIEW [Current Product List] \nAS\nSELEC...
22,view,Customer and Suppliers by City,Customer and Suppliers by City,0,CREATE VIEW [Customer and Suppliers by City] \...
23,view,Invoices,Invoices,0,CREATE VIEW [Invoices] \nAS\nSELECT Orders.Shi...
24,view,Orders Qry,Orders Qry,0,CREATE VIEW [Orders Qry] AS\nSELECT Orders.Ord...
25,view,Order Subtotals,Order Subtotals,0,CREATE VIEW [Order Subtotals] AS\nSELECT [Orde...
26,view,Product Sales for 1997,Product Sales for 1997,0,CREATE VIEW [Product Sales for 1997] AS\nSELEC...
27,view,Products Above Average Price,Products Above Average Price,0,CREATE VIEW [Products Above Average Price] AS\...
28,view,Products by Category,Products by Category,0,CREATE VIEW [Products by Category] AS\nSELECT ...
29,view,Quarterly Orders,Quarterly Orders,0,CREATE VIEW [Quarterly Orders] AS\nSELECT DIST...
30,view,Sales Totals by Amount,Sales Totals by Amount,0,CREATE VIEW [Sales Totals by Amount] AS\nSELEC...
31,view,Summary of Sales by Quarter,Summary of Sales by Quarter,0,CREATE VIEW [Summary of Sales by Quarter] AS\n...
32,view,Summary of Sales by Year,Summary of Sales by Year,0,CREATE VIEW [Summary of Sales by Year] AS\nSEL...
33,view,Category Sales for 1997,Category Sales for 1997,0,CREATE VIEW [Category Sales for 1997] AS\nSELE...
34,view,Order Details Extended,Order Details Extended,0,CREATE VIEW [Order Details Extended] AS\nSELEC...
35,view,Sales by Category,Sales by Category,0,CREATE VIEW [Sales by Category] AS\nSELECT Cat...
36,view,ProductDetails_V,ProductDetails_V,0,CREATE VIEW [ProductDetails_V] as\nselect \np....

In [4]:
tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

# Show Table Schemas
tables

                    name
0             Categories
1        sqlite_sequence
2   CustomerCustomerDemo
3   CustomerDemographics
4              Customers
5              Employees
6    EmployeeTerritories
7          Order Details
8                 Orders
9               Products
10               Regions
11              Shippers
12             Suppliers
13           Territories

In [5]:
customers_df = pd.read_sql_query(
    "SELECT * FROM Customers;",
    conn
)

customers_df.head()

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,Western Europe,12209,Germany,030-0074321,030-0076545
1,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,Central America,05021,Mexico,(5) 555-4729,(5) 555-3745
2,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,Central America,05023,Mexico,(5) 555-3932,None
3,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,British Isles,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
4,BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Luleå,Northern Europe,S-958 22,Sweden,0921-12 34 65,0921-12 34 67

In [6]:
orders_df = pd.read_sql_query(
    'SELECT * FROM Orders;',
    conn
)

orders_df.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipVia,Freight,ShipName,ShipAddress,ShipCity,ShipRegion,ShipPostalCode,ShipCountry
0,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,Reims,Western Europe,51100,France
1,10249,TOMSP,6,2016-07-05,2016-08-16,2016-07-10,1,22.25,Toms Spezialitäten,Luisenstr. 48,Münster,Western Europe,44087,Germany
2,10250,HANAR,4,2016-07-08,2016-08-05,2016-07-12,2,25.00,Hanari Carnes,"Rua do Paço, 67",Rio de Janeiro,South America,05454-876,Brazil
3,10251,VICTE,3,2016-07-08,2016-08-05,2016-07-15,1,20.25,Victuailles en stock,"2, rue du Commerce",Lyon,Western Europe,69004,France
4,10252,SUPRD,4,2016-07-09,2016-08-06,2016-07-11,2,36.25,Suprêmes délices,"Boulevard Tirou, 255",Charleroi,Western Europe,B-6000,Belgium

In [7]:
order_details_df = pd.read_sql_query(
    'SELECT * FROM "Order Details";',
    conn 
)

order_details_df.head()

   OrderID  ProductID  UnitPrice  Quantity  Discount
0    10248         11       14.0        12       0.0
1    10248         42        9.8        10       0.0
2    10248         72       34.8         5       0.0
3    10249         14       18.6         9       0.0
4    10249         51       42.4        40       0.0

In [8]:
products_df = pd.read_sql_query(
    'SELECT * FROM Products;',
    conn
)

products_df.head()

,ProductID,ProductName,SupplierID,CategoryID,QuantityPerUnit,UnitPrice,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued
0,1,Chai,1,1,10 boxes x 20 bags,18.00,39,0,10,0
1,2,Chang,1,1,24 - 12 oz bottles,19.00,17,40,25,0
2,3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00,13,70,25,0
3,4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00,53,0,0,0
4,5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35,0,0,0,1

In [9]:
orders_enriched_df = orders_df.merge(order_details_df, on='OrderID', how='left'
    ).merge(products_df, on='ProductID', how='left'
    ).merge(customers_df, on='CustomerID', how='left')

orders_enriched_df.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipVia,Freight,ShipName,ShipAddress,...,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,...,Vins et alcools Chevalier,Paul Henriot,Accounting Manager,59 rue de l'Abbaye,Reims,Western Europe,51100,France,26.47.15.10,26.47.15.11
1,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,...,Vins et alcools Chevalier,Paul Henriot,Accounting Manager,59 rue de l'Abbaye,Reims,Western Europe,51100,France,26.47.15.10,26.47.15.11
2,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,...,Vins et alcools Chevalier,Paul Henriot,Accounting Manager,59 rue de l'Abbaye,Reims,Western Europe,51100,France,26.47.15.10,26.47.15.11
3,10249,TOMSP,6,2016-07-05,2016-08-16,2016-07-10,1,22.25,Toms Spezialitäten,Luisenstr. 48,...,Toms Spezialitäten,Karin Josephs,Marketing Manager,Luisenstr. 48,Münster,Western Europe,44087,Germany,0251-031259,0251-035695
4,10249,TOMSP,6,2016-07-05,2016-08-16,2016-07-10,1,22.25,Toms Spezialitäten,Luisenstr. 48,...,Toms Spezialitäten,Karin Josephs,Marketing Manager,Luisenstr. 48,Münster,Western Europe,44087,Germany,0251-031259,0251-035695

In [10]:
df_cleaned = (
    orders_enriched_df
    .drop(columns=[c for c in orders_enriched_df.columns if c.endswith('_y')])
    .rename(columns=lambda x: x.replace('_x', ''))
    # Important to keep data (if not ML).
    # .drop(columns=['Country', 'ShipCountry'], errors='ignore')
)

df_cleaned.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipVia,Freight,ShipName,ShipAddress,...,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,...,Vins et alcools Chevalier,Paul Henriot,Accounting Manager,59 rue de l'Abbaye,Reims,Western Europe,51100,France,26.47.15.10,26.47.15.11
1,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,...,Vins et alcools Chevalier,Paul Henriot,Accounting Manager,59 rue de l'Abbaye,Reims,Western Europe,51100,France,26.47.15.10,26.47.15.11
2,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,...,Vins et alcools Chevalier,Paul Henriot,Accounting Manager,59 rue de l'Abbaye,Reims,Western Europe,51100,France,26.47.15.10,26.47.15.11
3,10249,TOMSP,6,2016-07-05,2016-08-16,2016-07-10,1,22.25,Toms Spezialitäten,Luisenstr. 48,...,Toms Spezialitäten,Karin Josephs,Marketing Manager,Luisenstr. 48,Münster,Western Europe,44087,Germany,0251-031259,0251-035695
4,10249,TOMSP,6,2016-07-05,2016-08-16,2016-07-10,1,22.25,Toms Spezialitäten,Luisenstr. 48,...,Toms Spezialitäten,Karin Josephs,Marketing Manager,Luisenstr. 48,Münster,Western Europe,44087,Germany,0251-031259,0251-035695

In [15]:
df_cleaned['OrderRevenue'] = (df_cleaned['UnitPrice'] - (df_cleaned['UnitPrice'] * df_cleaned['Discount'])) * df_cleaned['Quantity']
df_cleaned = df_cleaned.reset_index(names='LineItem')
df_cleaned

,LineItem,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipVia,Freight,ShipName,...,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax,OrderRevenue
0,0,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,...,Paul Henriot,Accounting Manager,59 rue de l'Abbaye,Reims,Western Europe,51100,France,26.47.15.10,26.47.15.11,168.00
1,1,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,...,Paul Henriot,Accounting Manager,59 rue de l'Abbaye,Reims,Western Europe,51100,France,26.47.15.10,26.47.15.11,98.00
2,2,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,...,Paul Henriot,Accounting Manager,59 rue de l'Abbaye,Reims,Western Europe,51100,France,26.47.15.10,26.47.15.11,174.00
3,3,10249,TOMSP,6,2016-07-05,2016-08-16,2016-07-10,1,22.25,Toms Spezialitäten,...,Karin Josephs,Marketing Manager,Luisenstr. 48,Münster,Western Europe,44087,Germany,0251-031259,0251-035695,167.40
4,4,10249,TOMSP,6,2016-07-05,2016-08-16,2016-07-10,1,22.25,Toms Spezialitäten,...,Karin Josephs,Marketing Manager,Luisenstr. 48,Münster,Western Europe,44087,Germany,0251-031259,0251-035695,1696.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609278,609278,26529,DUMON,6,2023-01-10 05:40:51,2023-02-21 23:37:27,2023-01-10 09:47:23,2,447.25,Seven Seas Imports,...,Janine Labrune,Owner,"67, rue des Cinquante Otages",Nantes,Western Europe,44000,France,40.67.88.88,40.67.89.89,806.00
609279,609279,26529,DUMON,6,2023-01-10 05:40:51,2023-02-21 23:37:27,2023-01-10 09:47:23,2,447.25,Seven Seas Imports,...,Janine Labrune,Owner,"67, rue des Cinquante Otages",Nantes,Western Europe,44000,France,40.67.88.88,40.67.89.89,216.00
609280,609280,26529,DUMON,6,2023-01-10 05:40:51,2023-02-21 23:37:27,2023-01-10 09:47:23,2,447.25,Seven Seas Imports,...,Janine Labrune,Owner,"67, rue des Cinquante Otages",Nantes,Western Europe,44000,France,40.67.88.88,40.67.89.89,93.69
609281,609281,26529,DUMON,6,2023-01-10 05:40:51,2023-02-21 23:37:27,2023-01-10 09:47:23,2,447.25,Seven Seas Imports,...,Janine Labrune,Owner,"67, rue des Cinquante Otages",Nantes,Western Europe,44000,France,40.67.88.88,40.67.89.89,1053.60
609282,609282,26529,DUMON,6,2023-01-10 05:40:51,2023-02-21 23:37:27,2023-01-10 09:47:23,2,447.25,Seven Seas Imports,...,Janine Labrune,Owner,"67, rue des Cinquante Otages",Nantes,Western Europe,44000,France,40.67.88.88,40.67.89.89,1014.00

In [20]:
import base64
from ydata_profiling import ProfileReport

with open("logo.png", "rb") as f:
    image_data = base64.b64encode(f.read()).decode("utf-8")
    logo_base64 = f"data:image/png;base64,{image_data}"

with plt.style.context("fivethirtyeight"):
    profile = ProfileReport(
        df_cleaned, 
        title='LENA Northwind EDA',
        dataset={
            "description": "Personal EDA for the development of a data analytics framework under LENA.",
            "author": "Zach Alabastro",
            "name": "Northwind Dataset",
            "url": "https://github.com/jpwhite3/northwind-SQLite3?tab=readme-ov-file"
        },
        plot={"dpi": 200, "image_format": "png"},
        html={
            "navbar_show": True,
            "full_width": True,
            "style": {
                "theme": "flatly",
                "logo": logo_base64
            }
        }
    )

profile.to_file('enriched_northwind.html')

100%|██████████| 38/38 [00:06<00:00,  6.21it/s]7<00:01,  4.34it/s, Describe variable: OrderRevenue]
Summarize dataset: 100%|██████████| 244/244 [00:29<00:00,  8.34it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:04<00:00,  4.46s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  6.40it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 46.57it/s]